### ISSUE TITLE
Setup not backed up

### ISSUE THREAD

**Issue by Potato-007** [X1a0He/Adobe-Downloader#3]
Hi, can you please explain this warning message. I tried re-opening the app several times without ever entering the pw for this setup to be backed up, and it remembered what apps were downloaded, and I could install them.
So I see no reason entering my password to backup the setup, as it's not even clear what a 'setup' means in this case.

Also, please clarify exactly what is saved where.

My major concern is however this: on macos the password is handled by the Authorization Services API when asked in a prompt and this ensures that the password is not exposed to the application and remains secure. With this app it's not true, and there's no way to tell if the pw is transmitted via internet to anyone or not. This is a big security risk.

a fantastic app by the way!

**Comment by X1a0He** [comment]
> Hi, can you please explain this warning message. I tried re-opening the app several times without ever entering the pw for this setup to be backed up, and it remembered what apps were downloaded, and I could install them.
> 
> So I see no reason entering my password to backup the setup, as it's not even clear what a 'setup' means in this case.
> 
> 
> 
> Also, please clarify exactly what is saved where.
> 
> 
> 
> My major concern is however this: on macos the password is handled by the Authorization Services API when asked in a prompt and this ensures that the password is not exposed to the application and remains secure. With this app it's not true, and there's no way to tell if the pw is transmitted via internet to anyone or not. This is a big security risk.
> 
> 
> 
> a fantastic app by the way!
> 
> 

I'm glad you like my work and understand that you have some confusion about the warning message. For the current Adobe Downloader, if you need to install apps, you will need the official "Setup" program from Adobe. If you don't handle it, you will encounter error 2700, just like with the predecessor Drovosek01/adobe-packager. I need to handle the "Setup" program, so I made a backup before processing it to facilitate user restoration. If you haven't backed it up, it might be because it was processed before you reopened Adobe Downloader. Rest assured, all code is open-source, so you don’t have to worry about security issues. Your data is very safe, and if you have any questions, you can find the corresponding processing logic in the code. I’m happy to answer your questions.
